# Generated by Django 4.2.13 on 2024-07-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="etude", name="representant",),
    ]
