# Generated by Django 4.2.13 on 2024-06-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="TVA_per",
            field=models.IntegerField(
                choices=[("20", "France"), ("0", "Etranger")], default="20"
            ),
        ),
    ]
