# Generated by Django 5.0.1 on 2024-02-09 21:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models
from polls.models import JE


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etude',
            name='en_negociation',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='je',
            name='chiffres_affaires',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='je',
            field=models.ForeignKey(default=JE.objects.get(pk='bab6b8bec2744faeb6343c6a40968534'), on_delete=django.db.models.deletion.CASCADE, to='polls.je'),
        ),
        migrations.AlterField(
            model_name='etude',
            name='je',
            field=models.ForeignKey(default=JE.objects.get(pk='bab6b8bec2744faeb6343c6a40968534'), on_delete=django.db.models.deletion.CASCADE, to='polls.je'),
        ),
        migrations.AlterField(
            model_name='je',
            name='BIC',
            field=models.CharField(max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Special characters are not allowed.')]),
        ),
        migrations.AlterField(
            model_name='je',
            name='IBAN',
            field=models.CharField(max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Special characters are not allowed.')]),
        ),
        migrations.AlterField(
            model_name='je',
            name='TVA',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}[0-9]{11}$', 'The expected format is 2 letters and 11 digits'), django.core.validators.MinLengthValidator(13, 'This field must contain exactly 13 characters.')]),
        ),
        migrations.AlterField(
            model_name='je',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='je',
            name='siret',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'This field must only contain digits'), django.core.validators.MinLengthValidator(14, 'This field must contain exactly 14 characters.')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='je',
            field=models.ForeignKey(default=JE.objects.get(pk='bab6b8bec2744faeb6343c6a40968534'), on_delete=django.db.models.deletion.CASCADE, to='polls.je'),
        ),
        migrations.AlterField(
            model_name='message',
            name='je',
            field=models.ForeignKey(default=JE.objects.get(pk='bab6b8bec2744faeb6343c6a40968534'), on_delete=django.db.models.deletion.CASCADE, to='polls.je'),
        ),
        migrations.AlterField(
            model_name='student',
            name='je',
            field=models.ForeignKey(default=JE.objects.get(pk='bab6b8bec2744faeb6343c6a40968534'), on_delete=django.db.models.deletion.CASCADE, to='polls.je'),
        ),
    ]
