# Generated by Django 4.2.14 on 2024-07-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="representant",
            name="contacte_2m",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="representant",
            name="reponse_2m",
            field=models.BooleanField(default=False),
        ),
    ]
