# Generated by Django 4.2.14 on 2024-08-01 12:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="member", name="president",),
        migrations.RemoveField(model_name="member", name="tresorier",),
        migrations.AddField(
            model_name="member",
            name="poste",
            field=models.CharField(
                choices=[
                    ("PRESIDENT", "président"),
                    ("VICE_PRESIDENT", "vice-président"),
                    ("TRESORIER", "Trésorier"),
                    ("VICE_TRESORIER", "vice-trésorier"),
                    ("SECRETAIRE_GENERALE", "secrétaire générale"),
                    ("CHEF_DE_PROJET", "chef de projet"),
                    ("DIRECTEUR_COMMERCIALE", "directeur commerciale"),
                    ("DIRECTEUR_PROJET", "directeur projet"),
                    ("DSI", "DSI"),
                    ("RESPONSABLE_QUALITE", "responsable_qualite"),
                    ("DIRECTEUR_COMMUNICATION", "directeur communication"),
                    ("DIRECTEUR_RSE", "directeur RSE"),
                ],
                default="PRESIDENT",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="representant",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.client",
            ),
        ),
        migrations.AlterField(
            model_name="representant",
            name="contact_recent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="representant",
            name="contenu_mail",
            field=models.CharField(
                blank=True,
                default=" Bonjour {{titre}} {{last_name}}, Je me permets de vous contacter au nom de la Junior Entrprise des Ponts. J'ai remarqué que nous avons effectué une mission pour vous il y a deux ans...",
                max_length=5000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="representant",
            name="contenu_reponse",
            field=models.CharField(
                blank=True, default="rien", max_length=5000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="representant",
            name="date_mail",
            field=models.DateField(
                blank=True, default=datetime.date(1747, 1, 1), null=True
            ),
        ),
        migrations.AlterField(
            model_name="representant",
            name="date_reponse",
            field=models.DateField(
                blank=True, default=datetime.date(1747, 1, 1), null=True
            ),
        ),
        migrations.AlterField(
            model_name="representant",
            name="fonction",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
