# Generated by Django 4.2.13 on 2024-07-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="duree_semaine",
            field=models.IntegerField(default=1),
        ),
    ]
