# Generated by Django 4.2.11 on 2024-05-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametresutilisateur",
            name="param_col_etude_remarque",
            field=models.BooleanField(default=True, verbose_name="Remarque"),
        ),
        migrations.AlterField(
            model_name="parametresutilisateur",
            name="param_col_etude_avancement",
            field=models.BooleanField(default=True, verbose_name="Avancement"),
        ),
        migrations.AlterField(
            model_name="parametresutilisateur",
            name="param_col_etude_client",
            field=models.BooleanField(default=True, verbose_name="Client"),
        ),
        migrations.AlterField(
            model_name="parametresutilisateur",
            name="param_col_etude_montant_HT",
            field=models.BooleanField(default=False, verbose_name="Montant HT"),
        ),
        migrations.AlterField(
            model_name="parametresutilisateur",
            name="param_col_etude_numero",
            field=models.BooleanField(default=True, verbose_name="Numéro"),
        ),
        migrations.AlterField(
            model_name="parametresutilisateur",
            name="param_col_etude_responsable",
            field=models.BooleanField(default=True, verbose_name="Responsable"),
        ),
        migrations.AlterField(
            model_name="parametresutilisateur",
            name="param_col_etude_titre",
            field=models.BooleanField(default=True, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="parametresutilisateur",
            name="param_statut_etude_ec",
            field=models.BooleanField(default=True, verbose_name="En cours"),
        ),
        migrations.AlterField(
            model_name="parametresutilisateur",
            name="param_statut_etude_ed",
            field=models.BooleanField(default=False, verbose_name="En discussion"),
        ),
        migrations.AlterField(
            model_name="parametresutilisateur",
            name="param_statut_etude_t",
            field=models.BooleanField(default=False, verbose_name="Terminée"),
        ),
    ]
