# Generated by Django 5.0.6 on 2024-07-07 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etude',
            name='debut',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
