# Generated by Django 4.2.11 on 2024-05-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conventioncadre",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="conventionetude",
            name="numero",
        ),
        migrations.AddField(
            model_name="etude",
            name="type_convention",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Convention cadre", "Cadre"),
                    ("Convention d'étude", "Etude"),
                ],
                verbose_name="Type de convention",
            ),
        ),
        migrations.AlterField(
            model_name="boncommande",
            name="fichier",
            field=models.FileField(storage="polls/", upload_to="polls/"),
        ),
        migrations.AlterField(
            model_name="client",
            name="logo",
            field=models.ImageField(upload_to="polls/"),
        ),
        migrations.AlterField(
            model_name="conventioncadre",
            name="fichier",
            field=models.FileField(storage="polls/", upload_to="polls/"),
        ),
        migrations.AlterField(
            model_name="conventionetude",
            name="fichier",
            field=models.FileField(storage="polls/", upload_to="polls/"),
        ),
        migrations.AlterField(
            model_name="devis",
            name="fichier",
            field=models.FileField(storage="polls/", upload_to="polls/"),
        ),
        migrations.AlterField(
            model_name="facture",
            name="fichier",
            field=models.FileField(storage="polls/", upload_to="polls/"),
        ),
        migrations.AlterField(
            model_name="facture",
            name="type_facture",
            field=models.CharField(
                choices=[
                    ("Facture d'acompte", "Acompte"),
                    ("Facture intermédiaire", "Intermediaire"),
                    ("Facture de solde", "Solde"),
                ],
                default="Facture de solde",
                max_length=30,
            ),
        ),
    ]
