# Generated by Django 5.0.4 on 2024-05-07 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etude',
            name='responsable',
        ),
        migrations.AlterField(
            model_name='etude',
            name='resp_qualite',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualite_etudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Responsable',
        ),
        migrations.AddField(
            model_name='etude',
            name='responsable',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_etudes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
