# Generated by Django 4.2.14 on 2024-07-31 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="representant",
            name="je",
            field=models.ForeignKey(
                default="f2fcbeb4-455e-4607-b535-f801ed1d20e1", on_delete=django.db.models.deletion.CASCADE, to="polls.je"
            ),
            preserve_default=False,
        ),
    ]
