# Generated by Django 4.2.11 on 2024-07-28 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="representant",
            name="je",
        ),
        migrations.AlterField(
            model_name="notification",
            name="utilisateur",
            field=models.ManyToManyField(
                blank=True, related_name="notifications", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
