# Generated by Django 4.2.7 on 2024-01-08 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raison_sociale", models.CharField(max_length=200)),
                ("adress", models.CharField(max_length=200)),
                (
                    "siret",
                    models.CharField(
                        max_length=14,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]+$", "This field must only contain digits"
                            ),
                            django.core.validators.MinLengthValidator(
                                14, "This field must contain exactly 14 caracters."
                            ),
                        ],
                    ),
                ),
                (
                    "APE",
                    models.CharField(
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{4}[A-Za-z]$", "The expected format is 0000A."
                            )
                        ],
                    ),
                ),
                (
                    "TVA",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z]{2}[0-9]{11}$",
                                "The expected format is 2 letters and 11 digits",
                            ),
                            django.core.validators.MinLengthValidator(
                                13, "This field must contain exactly 13 caracters."
                            ),
                        ],
                    ),
                ),
                (
                    "IBAN",
                    models.CharField(
                        max_length=34,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9]+$", "Special caracters are not allowed."
                            )
                        ],
                    ),
                ),
                (
                    "BIC",
                    models.CharField(
                        max_length=34,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9]+$", "Special caracters are not allowed."
                            )
                        ],
                    ),
                ),
                ("check_order", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
