# Generated by Django 4.2.14 on 2024-07-21 14:33

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="etude",
            name="representant_client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.representant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="representant",
            name="je",
            field=models.ForeignKey(
                default="96d2c7ee-6d6f-486a-86dd-1a7183b012b3",
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.je",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="code_postal",
            field=models.CharField(default="77420", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="numero_ss",
            field=models.CharField(
                default="0",
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]+$", "This field must only contain digits"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="ville",
            field=models.CharField(
                default="Champs-sur-Marne", max_length=300, null=True
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="pourcentage_JEH",
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name="facture",
            name="pourcentage_frais",
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name="facture",
            name="type_facture",
            field=models.CharField(
                choices=[
                    ("Facture d'acompte", "Acompte"),
                    ("Facture intermédiaire", "Intermediaire"),
                    ("Facture de solde", "Solde"),
                ],
                default="Facture d'acompte",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="debut_relatif",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="phase",
            name="duree_semaine",
            field=models.IntegerField(default=2),
        ),
    ]
