# Generated by Django 5.0.6 on 2024-05-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='_type',
            field=models.CharField(choices=[('GRANDE_ENTREPRISE', 'Grande entreprise'), ('SECTEUR_PUBLIC', 'Secteur Public'), ('START_UP_ET_TPE', 'Start-up et TPE'), ('PME', 'Petite et moyenne entreprise'), ('ETI', 'Entreprise de taille intermédiaire'), ('ASSOCIATION', 'Association')], default='SECTEUR_PUBLIC', help_text="Sélectionnez le type d'entreprise.", max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='secteur',
            field=models.CharField(choices=[('INDUSTRIE', 'Industrie'), ('DISTRIBUTION', 'Distribution'), ('SECTEUR_PUBLIC', 'Secteur Public'), ('CONSEIL', 'Conseil'), ('TRANSPORT', 'Transport'), ('NUMERIQUE', 'Numerique'), ('BTP', 'BTP'), ('AUTRE', 'Autre')], default='SECTEUR_PUBLIC', help_text="Sélectionnez le secteur d'activité du client.", max_length=20),
        ),
    ]
