# Generated by Django 4.2.14 on 2024-07-31 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_representant_je"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representant",
            name="contact_recent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="representant",
            name="contenu_mail",
            field=models.CharField(
                blank=True,
                default=" Bonjour {{titre}} {{last_name}}, Je me permets de vous contacter au nom de la Junior Entrprise des Ponts. J'ai remarqué que nous avons effectué une mission pour vous il y a deux ans...",
                max_length=5000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="representant",
            name="contenu_reponse",
            field=models.CharField(
                blank=True, default="rien", max_length=5000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="representant",
            name="date_mail",
            field=models.DateField(
                blank=True, default=datetime.date(1747, 1, 1), null=True
            ),
        ),
        migrations.AlterField(
            model_name="representant",
            name="date_reponse",
            field=models.DateField(
                blank=True, default=datetime.date(1747, 1, 1), null=True
            ),
        ),
    ]
