# Generated by Django 5.0.6 on 2024-07-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_etude_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='etude',
            name='tva_pourcentage',
            field=models.FloatField(default=20),
        ),
    ]
