# Generated by Django 4.2.11 on 2024-07-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_remove_representant_je_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="href_redirect",
            field=models.CharField(blank=True, null=True),
        ),
    ]
