# Generated by Django 4.2.13 on 2024-07-02 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_phase_duree_semaine"),
    ]

    operations = [
        migrations.RemoveField(model_name="facture", name="remarque",),
        migrations.AddField(
            model_name="facture", name="TVA_per", field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="facture",
            name="date_echeance",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="facture",
            name="date_emission",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="phase",
            name="date_debut",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="phase",
            name="date_fin",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
