# Generated by Django 4.2.11 on 2024-05-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_parametresutilisateur_param_col_etude_remarque_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boncommande",
            name="fichier",
        ),
        migrations.RemoveField(
            model_name="conventioncadre",
            name="fichier",
        ),
        migrations.RemoveField(
            model_name="conventionetude",
            name="fichier",
        ),
        migrations.RemoveField(
            model_name="devis",
            name="fichier",
        ),
        migrations.RemoveField(
            model_name="facture",
            name="fichier",
        ),
        migrations.AddField(
            model_name="boncommande",
            name="remarque",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conventioncadre",
            name="date_signature",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conventioncadre",
            name="remarque",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conventionetude",
            name="date_signature",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conventionetude",
            name="remarque",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devis",
            name="date_signature",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devis",
            name="remarque",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facture",
            name="remarque",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="logo",
            field=models.ImageField(
                default="media/polls/Logo_Ecole_des_Ponts_ParisTech.svg.png",
                upload_to="polls/",
            ),
        ),
    ]
