# Generated by Django 5.0.4 on 2024-05-07 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_etude_responsable_alter_etude_resp_qualite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etude',
            name='responsable',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_etudes', to=settings.AUTH_USER_MODEL),
        ),
    ]
