# Generated by Django 4.2.7 on 2024-01-08 19:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_je_delete_choice_delete_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("adress", models.CharField(max_length=300)),
                ("country", models.CharField(max_length=100)),
                (
                    "siret",
                    models.CharField(
                        default="12345678901234",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9]+$"),
                            django.core.validators.MinLengthValidator(
                                14, "This field must contain exactly 14 caracters."
                            ),
                        ],
                    ),
                ),
                (
                    "je",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.je",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Etude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("begin", models.DateField()),
                ("end", models.DateField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.client"
                    ),
                ),
                (
                    "je",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.je",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("mail", models.EmailField(max_length=200)),
                ("phone_number", models.CharField(blank=True, max_length=200)),
                ("adress", models.CharField(max_length=300)),
                ("country", models.CharField(max_length=100)),
                ("promotion", models.CharField(blank=True, max_length=200)),
                ("etudes", models.ManyToManyField(blank=True, to="polls.etude")),
                (
                    "je",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.je",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=100)),
                (
                    "je",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.je",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.student",
                    ),
                ),
            ],
        ),
    ]
