# Generated by Django 4.2.13 on 2024-06-23 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_facture_tva_per"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="date_echeance",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 6, 23, 17, 59, 1, 40138, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facture",
            name="date_emission",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 6, 23, 17, 59, 16, 205521, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="facture", name="TVA_per", field=models.IntegerField(default=20),
        ),
    ]
