# Generated by Django 4.2.14 on 2024-07-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_devis_date_etude_representant_client_representant_je_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representant",
            name="je",
            field=models.ForeignKey(
                default="96d2c7ee-6d6f-486a-86dd-1a7183b012b3",
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.je",
            ),
        ),
    ]
