# Generated by Django 4.2.14 on 2024-07-16 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_representant_contacte_2m_representant_reponse_2m"),
    ]

    operations = [
        migrations.RemoveField(model_name="representant", name="contacte_2m",),
        migrations.RemoveField(model_name="representant", name="je",),
        migrations.RemoveField(model_name="representant", name="reponse_2m",),
        migrations.AddField(
            model_name="representant",
            name="dernier_mail",
            field=models.DateField(default=datetime.date(1747, 1, 1)),
        ),
        migrations.AddField(
            model_name="representant",
            name="derniere_reponse",
            field=models.DateField(default=datetime.date(1747, 1, 1)),
        ),
    ]
