# Generated by Django 4.2.13 on 2024-07-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_remove_facture_remarque_facture_tva_per_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="debut_relatif",
            field=models.IntegerField(default=1),
        ),
    ]
