# Generated by Django 4.2.11 on 2024-05-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_remove_boncommande_fichier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvenantRuptureConventionEtude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("date_signature", models.DateField(blank=True, null=True)),
                ("remarque", models.TextField(blank=True, null=True)),
                (
                    "ce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avenants",
                        to="polls.conventionetude",
                    ),
                ),
            ],
        ),
    ]
