# Generated by Django 4.2.14 on 2024-07-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_remove_representant_contacte_2m_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="representant",
            name="contact_rec",
            field=models.BooleanField(default=False),
        ),
    ]
