# Generated by Django 4.2.14 on 2024-07-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_representant_je"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="president",
            field=models.BooleanField(default=True, verbose_name="président"),
        ),
        migrations.AddField(
            model_name="member",
            name="tresorier",
            field=models.BooleanField(default=True, verbose_name="tresorier"),
        ),
    ]
