# Generated by Django 4.2.13 on 2024-06-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_facture_date_echeance_facture_date_emission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="date_echeance",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="facture",
            name="date_emission",
            field=models.DateField(null=True),
        ),
    ]
