# Generated by Django 4.2.11 on 2024-07-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_notification_href_redirect"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvenantRDM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("date_signature", models.DateField(blank=True, null=True)),
                ("remarque", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="avenantconventionetude",
            name="liste_phases_supprimees",
        ),
        migrations.RemoveField(
            model_name="avenantruptureconventionetude",
            name="numero",
        ),
        migrations.AddField(
            model_name="rdm",
            name="eleve",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rdm",
                to="polls.student",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SuppressionPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avenant_ce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases_supprimees",
                        to="polls.avenantconventionetude",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppression",
                        to="polls.phase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModificationPhaseRDM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nouveau_nombre_JEH", models.IntegerField()),
                (
                    "avenant_rdm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases_modif_jeh",
                        to="polls.avenantrdm",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modif_jeh_rdm",
                        to="polls.phase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModificationJEHPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nouveau_nombre_JEH", models.IntegerField()),
                (
                    "avenant_ce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases_modif_jeh",
                        to="polls.avenantconventionetude",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modif_jeh",
                        to="polls.phase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModificationDureePhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nouvelle_duree", models.IntegerField()),
                (
                    "avenant_ce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases_modif_duree",
                        to="polls.avenantconventionetude",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modif_duree",
                        to="polls.phase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvenantRuptureRDM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_signature", models.DateField(blank=True, null=True)),
                ("remarque", models.TextField(blank=True, null=True)),
                (
                    "rdm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avenants",
                        to="polls.rdm",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="avenantrdm",
            name="rdm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avenants_modification",
                to="polls.rdm",
            ),
        ),
    ]
