# Generated by Django 5.0.4 on 2024-05-07 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_etude_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etude',
            name='resp_qualite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualite_etudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etude',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_etudes', to=settings.AUTH_USER_MODEL),
        ),
    ]
