# Generated by Django 4.2.14 on 2024-07-31 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_representant_contact_recent_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="representant", name="je",),
    ]
