# Generated by Django 5.0.4 on 2024-05-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_etude_resp_qualite_alter_etude_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='departement',
            field=models.CharField(choices=[('IMI', 'IMI'), ('SEGF', 'SEGF'), ('GMM', 'GMM'), ('1A', '1A'), ('GCC', 'GCC'), ('VET', 'VET'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
    ]
