# Generated by Django 4.2.13 on 2024-07-02 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_phase_debut_relatif"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="remarque",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="titre",
            field=models.CharField(
                choices=[("M.", "M."), ("Mme", "Mme")], default="M.", max_length=5
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Representant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        choices=[("M.", "M."), ("Mme", "Mme")], max_length=5
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("mail", models.EmailField(max_length=200)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("remarque", models.TextField(blank=True, default="", null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.client"
                    ),
                ),
                (
                    "je",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.je",
                    ),
                ),
            ],
        ),
    ]
