# Generated by Django 4.2.14 on 2024-07-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_member_president_member_tresorier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="fonction_representant",
            new_name="fonction_representant_legale",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="nom_representant",
            new_name="nom_representant_legale",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="titre_representant",
            new_name="titre_representant_legale",
        ),
        migrations.AddField(
            model_name="client",
            name="prenom_representant_legale",
            field=models.CharField(default="PEP", max_length=100),
            preserve_default=False,
        ),
    ]
