# Generated by Django 4.2.11 on 2024-07-31 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_avenantrdm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="supprimee",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ModificationDebutPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nouveau_debut", models.IntegerField()),
                (
                    "avenant_ce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases_modif_debut",
                        to="polls.avenantconventionetude",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modif_debut",
                        to="polls.phase",
                    ),
                ),
            ],
        ),
    ]
