# Generated by Django 4.2.13 on 2024-07-02 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_client_remarque_student_titre_representant"),
    ]

    operations = [
        migrations.RemoveField(model_name="representant", name="client",),
        migrations.AddField(
            model_name="client",
            name="representant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.representant",
            ),
        ),
    ]
