# Generated by Django 4.2.14 on 2024-07-21 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "polls",
            "0005_rename_fonction_representant_client_fonction_representant_legale_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RDM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_signature", models.DateField(blank=True, null=True)),
                ("remarque", models.TextField(blank=True, null=True)),
                (
                    "etude",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdm",
                        to="polls.etude",
                    ),
                ),
            ],
        ),
    ]
