# Generated by Django 5.0.6 on 2024-05-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_student_departement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etude',
            name='students',
        ),
    ]
