# Generated by Django 4.2.14 on 2024-07-21 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_rdm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client", name="fonction_representant_legale",
        ),
        migrations.RemoveField(model_name="client", name="nom_representant_legale",),
        migrations.RemoveField(model_name="client", name="prenom_representant_legale",),
        migrations.RemoveField(model_name="client", name="titre_representant_legale",),
        migrations.RemoveField(model_name="etude", name="representant_client",),
        migrations.AddField(
            model_name="etude",
            name="client_interlocuteur",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_interlocuteur",
                to="polls.representant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="etude",
            name="client_representant_legale",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_representant_legale",
                to="polls.representant",
            ),
            preserve_default=False,
        ),
    ]
