# Generated by Django 4.2.13 on 2024-07-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_remove_representant_client_client_representant"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="representant",),
        migrations.AddField(
            model_name="representant",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.client",
            ),
        ),
    ]
