# Generated by Django 5.0.6 on 2024-05-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_etude_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='secteur',
            field=models.CharField(choices=[('GRANDE_ENTREPRISE', 'Grande entreprise'), ('SECTEUR_PUBLIC', 'Secteur public'), ('START_UP_ET_TPE', 'Start-up et TPE'), ('PME', 'Petite et moyenne entreprise'), ('ETI', 'Entreprise de taille intermédiaire'), ('ASSOCIATION', 'Association')], default='SECTEUR_PUBLIC', help_text="Sélectionnez le secteur d'activité du client.", max_length=20),
        ),
    ]
