# Generated by Django 4.2.14 on 2024-07-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_remove_client_fonction_representant_legale_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="representant",
            old_name="contact_rec",
            new_name="contact_recent",
        ),
        migrations.RenameField(
            model_name="representant", old_name="dernier_mail", new_name="date_mail",
        ),
        migrations.RenameField(
            model_name="representant",
            old_name="derniere_reponse",
            new_name="date_reponse",
        ),
        migrations.AddField(
            model_name="representant",
            name="contenu_mail",
            field=models.CharField(
                default=" Bonjour {{repr.titre}} {{repr.last_name}}, Je me permets de vous contacter au nom de la Junior Entrprise des Ponts. J'ai remarqué que nous avons effectué une mission pour vous il y a deux ans...",
                max_length=5000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="representant",
            name="contenu_reponse",
            field=models.CharField(default="rien", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="representant",
            name="demarchage",
            field=models.CharField(
                choices=[
                    ("A_CONTACTER", "A contacter"),
                    ("ATTENTE_REPONSE", "Attente d'un retour"),
                    ("RELANCER", "A relancer"),
                    ("RETOUR_RECU", "Retour reçu"),
                    ("ETUDE_CREEE", "Étude créée"),
                    ("ATTENDRE", "Attendre avant prochain mail"),
                ],
                default="A_CONTACTER",
                max_length=40,
            ),
        ),
    ]
