# Generated by Django 4.2.13 on 2024-07-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_remove_client_representant_representant_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="representant",
            name="fonction",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
