# Generated by Django 4.2.13 on 2024-07-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_representant_fonction"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="description",
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="etude",
            name="problematique",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="je", name="base_urssaf", field=models.FloatField(default=46.6),
        ),
        migrations.AddField(
            model_name="je", name="taux_ATMP", field=models.FloatField(default=0.66),
        ),
        migrations.AddField(
            model_name="je",
            name="taux_cotisations",
            field=models.FloatField(default=29.9),
        ),
    ]
