# Generated by Django 4.2.7 on 2024-02-25 09:36

from django.db import migrations, models
import django.db.models.deletion
from polls.models import JE


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_alter_client_je_alter_etude_je_alter_member_je_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etude",
            name="montant_HT",
        ),
        migrations.RemoveField(
            model_name="etude",
            name="nb_JEH",
        ),
        migrations.AlterField(
            model_name="client",
            name="je",
            field=models.ForeignKey(
                default=JE.objects.get(pk="bab6b8bec2744faeb6343c6a40968534"),
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.je",
            ),
        ),
        migrations.AlterField(
            model_name="etude",
            name="je",
            field=models.ForeignKey(
                default=JE.objects.get(pk="bab6b8bec2744faeb6343c6a40968534"),
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.je",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="je",
            field=models.ForeignKey(
                default=JE.objects.get(pk="bab6b8bec2744faeb6343c6a40968534"),
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.je",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="je",
            field=models.ForeignKey(
                default=JE.objects.get(pk="bab6b8bec2744faeb6343c6a40968534"),
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.je",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="je",
            field=models.ForeignKey(
                default=JE.objects.get(pk="bab6b8bec2744faeb6343c6a40968534"),
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.je",
            ),
        ),
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant_JEH", models.FloatField()),
                ("numero", models.IntegerField()),
                (
                    "etude",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.etude"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssignationJEH",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pourcentage_retribution", models.FloatField()),
                ("nombre_JEH", models.IntegerField()),
                (
                    "eleve",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.student"
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.phase"
                    ),
                ),
            ],
        ),
    ]
