# Generated by Django 4.2.14 on 2024-07-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_rename_contact_rec_representant_contact_recent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representant",
            name="contenu_mail",
            field=models.CharField(
                default=" Bonjour {{titre}} {{last_name}}, Je me permets de vous contacter au nom de la Junior Entrprise des Ponts. J'ai remarqué que nous avons effectué une mission pour vous il y a deux ans...",
                max_length=5000,
                null=True,
            ),
        ),
    ]
