# Generated by Django 4.2.14 on 2024-07-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_alter_representant_contenu_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representant",
            name="demarchage",
            field=models.CharField(
                choices=[
                    ("A_CONTACTER", "A contacter"),
                    ("ATTENTE_REPONSE", "Attente d'un retour"),
                    ("RELANCER", "A relancer"),
                    ("RETOUR_RECU", "Retour reçu"),
                    ("ETUDE_CREEE", "Étude créée"),
                ],
                default="A_CONTACTER",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="representant",
            name="remarque",
            field=models.TextField(blank=True, default="RAS", null=True),
        ),
    ]
