# Generated by Django 4.2.13 on 2024-07-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_client_description_etude_problematique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etude",
            name="duree_semaine",
            field=models.IntegerField(default=1),
        ),
    ]
