# Generated by Django 4.2.13 on 2024-07-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0010_alter_etude_duree_semaine"),
    ]

    operations = [
        migrations.RemoveField(model_name="etude", name="duree_semaine",),
    ]
