# Generated by Django 4.2.14 on 2024-07-30 20:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0010_alter_representant_demarchage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("date_signature", models.DateField(blank=True, null=True)),
                ("remarque", models.TextField(blank=True, null=True)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "etude",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pv",
                        to="polls.etude",
                    ),
                ),
            ],
        ),
    ]
