# Generated by Django 4.2.13 on 2024-07-02 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_remove_etude_duree_semaine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etude",
            name="debut",
            field=models.DateField(default=datetime.date(1969, 1, 1)),
        ),
    ]
