# Generated by Django 4.2.13 on 2024-07-02 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0013_remove_facture_montant_ht"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="fonction_representant",),
        migrations.RemoveField(model_name="client", name="nom_representant",),
        migrations.RemoveField(model_name="client", name="titre_representant",),
        migrations.AddField(
            model_name="etude",
            name="representant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.representant",
            ),
        ),
    ]
