# Generated by Django 4.2.13 on 2024-07-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0014_remove_client_fonction_representant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="fonction_representant",
            field=models.CharField(default="chercheur", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="nom_representant",
            field=models.CharField(default="feord", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="titre_representant",
            field=models.CharField(
                choices=[("M.", "M."), ("Mme", "Mme")], default="M.", max_length=5
            ),
            preserve_default=False,
        ),
    ]
