# Generated by Django 4.2.7 on 2024-01-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="adress",
        ),
        migrations.AddField(
            model_name="client",
            name="code_postal",
            field=models.CharField(default=77420, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="raison_sociale",
            field=models.CharField(default="CEERMICS", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="representant",
            field=models.CharField(default="Julien Guyon", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="rue",
            field=models.CharField(default="6-8 Avenue Blaise Pascal", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="ville",
            field=models.CharField(default="Champs-sur-Marne", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="etude",
            name="montant_HT",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="etude",
            name="nb_JEH",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="member",
            name="student",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.student",
            ),
        ),
    ]
