# Generated by Django 4.2.7 on 2024-01-24 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="je",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="polls.je"
            ),
        ),
    ]
