# Generated by Django 4.2.7 on 2024-01-15 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_remove_user_name_alter_user_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="polls.student",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="student",
            name="etudes",
        ),
        migrations.AddField(
            model_name="etude",
            name="students",
            field=models.ManyToManyField(blank=True, to="polls.student"),
        ),
    ]
