# Generated by Django 4.2.7 on 2024-01-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_message_je"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
