# Generated by Django 4.2.7 on 2024-01-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_member_remove_student_etudes_etude_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="etude",
            name="responsable",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.member",
            ),
        ),
    ]
